=== mohab567/DBMS/Project_012_DBMS/DatabaseRepository/Mohab/lolo.dtd
<!ELEMENT parent (lolo*)>
<!ELEMENT lolo (id,koko)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT koko (#PCDATA)>

<!ATTLIST id type CDATA "int">
<!ATTLIST koko type CDATA "date">

=== mohab567/DBMS/Project_012_DBMS/DatabaseRepository/Mohab/lolo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE parent SYSTEM "lolo.dtd">
<parent>
<lolo><id type="int">1</id><koko type="date">1996-7-7</koko></lolo><lolo><id type="int">1</id><koko type="date">null</koko></lolo><lolo><id type="int">1</id><koko type="date">null</koko></lolo><lolo><id type="int">1</id><koko type="date">1996-7-7</koko></lolo><lolo><id type="int">5</id><koko type="date">null</koko></lolo><lolo><id type="int">5</id><koko type="date">1998-4-4</koko></lolo><lolo><id type="int">5</id><koko type="date">1998-4-4</koko></lolo><lolo><id type="int">5</id><koko type="date">1998-4-4</koko></lolo><lolo><id type="int">5</id><koko type="date">1998-4-4</koko></lolo><lolo><id type="int">5</id><koko type="date">1998-4-4</koko></lolo><lolo><id type="int">2</id><koko type="date">null</koko></lolo><lolo><id type="int">2</id><koko type="date">1999-5-5</koko></lolo><lolo><id type="int">2</id><koko type="date">1999-3-3</koko></lolo><lolo><id type="int">2</id><koko type="date">1999-3-3</koko></lolo><lolo><id type="int">2</id><koko type="date">null</koko></lolo></parent>
